# These are supported funding model platforms

github: # Replace with up to 4 GitHub Sponsors-enabled usernames e.g., [user1, user2]
patreon: # ajarnspencer
open_collective: # M/A
ko_fi: # N/A
tidelift: # N/A
community_bridge: # N/A 
liberapay: # N/A
issuehunt: # N/A
lfx_crowdfunding: # N/A
polar: # N/A
buy_me_a_coffee: # https://buymeacoffee.com/ajarnspencer
custom: # Replace with up to 4 custom sponsorship URLs e.g., ['https://www.ajarnspencer.com', 'https://www.mastertheweb.net', 'https://www.ancientamulet.com']
